
/*
 * 
 */

package org.ow2.petals.transporter.impl.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.ow2.petals.transporter.Transporter;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Oct 08 10:58:52 CEST 2009
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "transporterService", 
		wsdlLocation = "transporter.wsdl",
		targetNamespace = "http://petals.ow2.org/transporter/") 
		public class TransporterService extends Service {

	public final static URL WSDL_LOCATION;
	public final static QName SERVICE = new QName("http://petals.ow2.org/transporter/", "transporterService");
	public final static QName TransporterImplPort = new QName("http://petals.ow2.org/transporter/", "TransporterImplPort");
	static {
		URL url = null;

		url = TransporterService.class.getClassLoader().getResource("transporter.wsdl");

		WSDL_LOCATION = url;
	}

	public TransporterService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public TransporterService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public TransporterService() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return
	 *     returns Transporter
	 */
	@WebEndpoint(name = "TransporterImplPort")
	public Transporter getTransporterImplPort() {
		return super.getPort(TransporterImplPort, Transporter.class);
	}

	/**
	 * 
	 * @param features
	 *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
	 * @return
	 *     returns Transporter
	 */
	@WebEndpoint(name = "TransporterImplPort")
	public Transporter getTransporterImplPort(WebServiceFeature... features) {
		return super.getPort(TransporterImplPort, Transporter.class, features);
	}

}
