/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.webservicex;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.1.3 Thu Jul 30 11:51:00 CEST 2009
 * Generated source version: 2.1.3
 * 
 */

@javax.jws.WebService(serviceName = "StockQuote", portName = "StockQuoteSoap1", targetNamespace = "http://www.webserviceX.NET/", wsdlLocation = "./src/test/resources/wsdl/stockquote.wsdl", endpointInterface = "net.webservicex.StockQuoteSoap")
public class StockQuoteSoapImpl implements StockQuoteSoap {

	private static final Logger LOG = Logger.getLogger(StockQuoteSoapImpl.class
			.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see net.webservicex.StockQuoteSoap#getQuote(java.lang.String symbol )*
	 */
	public java.lang.String getQuote(final java.lang.String symbol) {
		StockQuoteSoapImpl.LOG.info("Executing operation getQuote");
		System.out.println(symbol);
		try {
			final java.lang.String _return = "very much";
			return _return;
		} catch (final Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
