package net.webservicex;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.1.3 Thu Jul 30 11:51:00 CEST 2009
 * Generated source version: 2.1.3
 * 
 */

public class StockQuoteSoap_StockQuoteSoap3_Server {

	public static void main(final String args[]) throws Exception {
		new StockQuoteSoap_StockQuoteSoap3_Server();
		System.out.println("Server ready...");

		Thread.sleep(5 * 60 * 1000);
		System.out.println("Server exiting");
		System.exit(0);
	}

	protected StockQuoteSoap_StockQuoteSoap3_Server() throws Exception {
		System.out.println("Starting Server");
		final Object implementor = new StockQuoteSoapImpl();
		final String address = "http://localhost:9001/stockquote3";
		Endpoint.publish(address, implementor);
	}
}
