package org.petals.ow2.echo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Jul 29 11:02:01 CEST 2009
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://ow2.petals.org/echo/", name = "echo")
@XmlSeeAlso({ObjectFactory.class})
public interface Echo {

    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://ow2.petals.org/echo/", className = "org.petals.ow2.echo.EchoResponse")
    @RequestWrapper(localName = "echo", targetNamespace = "http://ow2.petals.org/echo/", className = "org.petals.ow2.echo.Echo_Type")
    @WebResult(name = "out", targetNamespace = "")
    @WebMethod(action = "http://ow2.petals.org/echo/echo")
    public java.lang.String echo(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );
}
