package org.petals.ow2.admin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Fri Jan 14 11:43:20 CET 2011
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "http://ow2.petals.org/Admin/", name = "Admin")
@XmlSeeAlso({ObjectFactory.class})
public interface Admin {

    @WebResult(name = "providerName", targetNamespace = "")
    @RequestWrapper(localName = "createProvider", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateProvider")
    @ResponseWrapper(localName = "createProviderResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateProviderResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/createProvider")
    public java.lang.String createProvider(
        @WebParam(name = "componentName", targetNamespace = "")
        javax.xml.namespace.QName componentName,
        @WebParam(name = "providerName", targetNamespace = "")
        javax.xml.namespace.QName providerName,
        @WebParam(name = "fractalProviderItfName", targetNamespace = "")
        java.lang.String fractalProviderItfName,
        @WebParam(name = "classProviderName", targetNamespace = "")
        java.lang.String classProviderName
    );

    @WebResult(name = "clientName", targetNamespace = "")
    @RequestWrapper(localName = "createClient", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateClient")
    @ResponseWrapper(localName = "createClientResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateClientResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/createClient")
    public java.lang.String createClient(
        @WebParam(name = "componentName", targetNamespace = "")
        javax.xml.namespace.QName componentName,
        @WebParam(name = "clientName", targetNamespace = "")
        javax.xml.namespace.QName clientName,
        @WebParam(name = "fractalClientItfName", targetNamespace = "")
        java.lang.String fractalClientItfName,
        @WebParam(name = "classClientName", targetNamespace = "")
        java.lang.String classClientName
    );

    @WebResult(name = "soapAddress", targetNamespace = "")
    @RequestWrapper(localName = "createServiceEndpointOnSoapClient", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateServiceEndpointOnSoapClient")
    @ResponseWrapper(localName = "createServiceEndpointOnSoapClientResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateServiceEndpointOnSoapClientResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/createServiceEndpointOnSoapClient")
    public java.lang.String createServiceEndpointOnSoapClient(
        @WebParam(name = "providerName", targetNamespace = "")
        javax.xml.namespace.QName providerName,
        @WebParam(name = "serviceName", targetNamespace = "")
        javax.xml.namespace.QName serviceName,
        @WebParam(name = "fractalServiceItfName", targetNamespace = "")
        java.lang.String fractalServiceItfName,
        @WebParam(name = "classServiceName", targetNamespace = "")
        java.lang.String classServiceName,
        @WebParam(name = "providerEndpointName", targetNamespace = "")
        java.lang.String providerEndpointName,
        @WebParam(name = "fractalProviderEndpointItfName", targetNamespace = "")
        java.lang.String fractalProviderEndpointItfName,
        @WebParam(name = "classProviderEndpointName", targetNamespace = "")
        java.lang.String classProviderEndpointName,
        @WebParam(name = "classProviderEndpointBehaviourName", targetNamespace = "")
        java.lang.String classProviderEndpointBehaviourName,
        @WebParam(name = "wsdl", targetNamespace = "")
        java.lang.String wsdl,
        @WebParam(name = "clientName", targetNamespace = "")
        javax.xml.namespace.QName clientName
    );

    @WebResult(name = "clientAndProviderName", targetNamespace = "")
    @RequestWrapper(localName = "createClientAndProvider", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateClientAndProvider")
    @ResponseWrapper(localName = "createClientAndProviderResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateClientAndProviderResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/createClientAndProvider")
    public java.lang.String createClientAndProvider(
        @WebParam(name = "componentName", targetNamespace = "")
        javax.xml.namespace.QName componentName,
        @WebParam(name = "clientAndProviderName", targetNamespace = "")
        javax.xml.namespace.QName clientAndProviderName,
        @WebParam(name = "fractalClientAndProviderInterfaceName", targetNamespace = "")
        java.lang.String fractalClientAndProviderInterfaceName,
        @WebParam(name = "classClientAndProviderName", targetNamespace = "")
        java.lang.String classClientAndProviderName,
        @WebParam(name = "fractalClientItfName", targetNamespace = "")
        java.lang.String fractalClientItfName,
        @WebParam(name = "classClientName", targetNamespace = "")
        java.lang.String classClientName,
        @WebParam(name = "fractalProviderItfName", targetNamespace = "")
        java.lang.String fractalProviderItfName,
        @WebParam(name = "classProviderName", targetNamespace = "")
        java.lang.String classProviderName
    );

    @WebResult(name = "clientEndpointName", targetNamespace = "")
    @RequestWrapper(localName = "createClientEndpoint", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateClientEndpoint")
    @ResponseWrapper(localName = "createClientEndpointResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateClientEndpointResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/createClientEndpoint")
    public java.lang.String createClientEndpoint(
        @WebParam(name = "clientName", targetNamespace = "")
        javax.xml.namespace.QName clientName,
        @WebParam(name = "clientEndpointName", targetNamespace = "")
        javax.xml.namespace.QName clientEndpointName,
        @WebParam(name = "fractalClientEndpointItfName", targetNamespace = "")
        java.lang.String fractalClientEndpointItfName,
        @WebParam(name = "classClientEndpointName", targetNamespace = "")
        java.lang.String classClientEndpointName,
        @WebParam(name = "classClientEndpointBehaviourName", targetNamespace = "")
        java.lang.String classClientEndpointBehaviourName
    );

    @WebResult(name = "endpointName", targetNamespace = "")
    @RequestWrapper(localName = "importSoapEndpoint", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.ImportSoapEndpoint")
    @ResponseWrapper(localName = "importSoapEndpointResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.ImportSoapEndpointResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/importSoapEndpoint")
    public java.lang.String importSoapEndpoint(
        @WebParam(name = "providerName", targetNamespace = "")
        javax.xml.namespace.QName providerName,
        @WebParam(name = "soapAddress", targetNamespace = "")
        java.lang.String soapAddress,
        @WebParam(name = "wsdl", targetNamespace = "")
        java.lang.String wsdl
    );

    @WebResult(name = "componentName", targetNamespace = "")
    @RequestWrapper(localName = "createComponent", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateComponent")
    @ResponseWrapper(localName = "createComponentResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateComponentResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/createComponent")
    public java.lang.String createComponent(
        @WebParam(name = "componentName", targetNamespace = "")
        javax.xml.namespace.QName componentName,
        @WebParam(name = "fractalItfName", targetNamespace = "")
        java.lang.String fractalItfName,
        @WebParam(name = "classComponentName", targetNamespace = "")
        java.lang.String classComponentName
    );

    @WebResult(name = "wsdmEndpointName", targetNamespace = "")
    @RequestWrapper(localName = "createMonitoringEndpoint", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateMonitoringEndpoint")
    @ResponseWrapper(localName = "createMonitoringEndpointResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateMonitoringEndpointResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/createMonitoringEndpoint")
    public java.lang.String createMonitoringEndpoint(
        @WebParam(name = "wsdmServiceName", targetNamespace = "")
        javax.xml.namespace.QName wsdmServiceName,
        @WebParam(name = "wsdmProviderEndpointName", targetNamespace = "")
        java.lang.String wsdmProviderEndpointName,
        @WebParam(name = "exposeInSoap", targetNamespace = "")
        boolean exposeInSoap
    );

    @WebResult(name = "providerEndpointName", targetNamespace = "")
    @RequestWrapper(localName = "createProviderEndpoint", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateProviderEndpoint")
    @ResponseWrapper(localName = "createProviderEndpointResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateProviderEndpointResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/createProviderEndpoint")
    public java.lang.String createProviderEndpoint(
        @WebParam(name = "serviceName", targetNamespace = "")
        javax.xml.namespace.QName serviceName,
        @WebParam(name = "providerEndpointName", targetNamespace = "")
        java.lang.String providerEndpointName,
        @WebParam(name = "fractalProviderEndpointItfName", targetNamespace = "")
        java.lang.String fractalProviderEndpointItfName,
        @WebParam(name = "classProviderEndpointName", targetNamespace = "")
        java.lang.String classProviderEndpointName,
        @WebParam(name = "classProviderEndpointBehaviourName", targetNamespace = "")
        java.lang.String classProviderEndpointBehaviourName,
        @WebParam(name = "wsdl", targetNamespace = "")
        java.lang.String wsdl
    );

    @WebResult(name = "soapAddress", targetNamespace = "")
    @RequestWrapper(localName = "wrapSoapEndpoint", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.WrapSoapEndpoint")
    @ResponseWrapper(localName = "wrapSoapEndpointResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.WrapSoapEndpointResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/wrapSoapEndpoint")
    public java.lang.String wrapSoapEndpoint(
        @WebParam(name = "providerName", targetNamespace = "")
        javax.xml.namespace.QName providerName,
        @WebParam(name = "soapAddress", targetNamespace = "")
        java.lang.String soapAddress,
        @WebParam(name = "wsdl", targetNamespace = "")
        java.lang.String wsdl,
        @WebParam(name = "interceptorClassName", targetNamespace = "")
        java.util.List<java.lang.String> interceptorClassName,
        @WebParam(name = "clientName", targetNamespace = "")
        javax.xml.namespace.QName clientName
    );

    @WebResult(name = "serviceName", targetNamespace = "")
    @RequestWrapper(localName = "createService", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateService")
    @ResponseWrapper(localName = "createServiceResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateServiceResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/createService")
    public java.lang.String createService(
        @WebParam(name = "providerName", targetNamespace = "")
        javax.xml.namespace.QName providerName,
        @WebParam(name = "serviceName", targetNamespace = "")
        javax.xml.namespace.QName serviceName,
        @WebParam(name = "fractalServiceItfName", targetNamespace = "")
        java.lang.String fractalServiceItfName,
        @WebParam(name = "classServiceName", targetNamespace = "")
        java.lang.String classServiceName
    );

    @WebResult(name = "endpointName", targetNamespace = "")
    @RequestWrapper(localName = "createServiceEndpoint", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateServiceEndpoint")
    @ResponseWrapper(localName = "createServiceEndpointResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.CreateServiceEndpointResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/createServiceEndpoint")
    public java.lang.String createServiceEndpoint(
        @WebParam(name = "providerName", targetNamespace = "")
        javax.xml.namespace.QName providerName,
        @WebParam(name = "serviceName", targetNamespace = "")
        javax.xml.namespace.QName serviceName,
        @WebParam(name = "fractalServiceItfName", targetNamespace = "")
        java.lang.String fractalServiceItfName,
        @WebParam(name = "classServiceName", targetNamespace = "")
        java.lang.String classServiceName,
        @WebParam(name = "providerEndpointName", targetNamespace = "")
        java.lang.String providerEndpointName,
        @WebParam(name = "fractalProviderEndpointItfName", targetNamespace = "")
        java.lang.String fractalProviderEndpointItfName,
        @WebParam(name = "classProviderEndpointName", targetNamespace = "")
        java.lang.String classProviderEndpointName,
        @WebParam(name = "classProviderEndpointBehaviourName", targetNamespace = "")
        java.lang.String classProviderEndpointBehaviourName,
        @WebParam(name = "wsdl", targetNamespace = "")
        java.lang.String wsdl
    );

    @WebResult(name = "soapAddress", targetNamespace = "")
    @RequestWrapper(localName = "addSoapListener", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.AddSoapListener")
    @ResponseWrapper(localName = "addSoapListenerResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.AddSoapListenerResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/addSoapListener")
    public java.lang.String addSoapListener(
        @WebParam(name = "clientEndpointName", targetNamespace = "")
        javax.xml.namespace.QName clientEndpointName
    );

    @WebResult(name = "soapAddress", targetNamespace = "")
    @RequestWrapper(localName = "exposeInSoapOnClient", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.ExposeInSoapOnClient")
    @ResponseWrapper(localName = "exposeInSoapOnClientResponse", targetNamespace = "http://ow2.petals.org/Admin/", className = "org.petals.ow2.admin.ExposeInSoapOnClientResponse")
    @WebMethod(action = "http://ow2.petals.org/Admin/exposeInSoapOnClient")
    public java.lang.String exposeInSoapOnClient(
        @WebParam(name = "serviceName", targetNamespace = "")
        javax.xml.namespace.QName serviceName,
        @WebParam(name = "providerEndpointName", targetNamespace = "")
        java.lang.String providerEndpointName,
        @WebParam(name = "clientName", targetNamespace = "")
        javax.xml.namespace.QName clientName
    );
}
