
package org.petals.ow2.admin;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Fri Jan 14 11:43:20 CET 2011
 * Generated source version: 2.2.2
 * 
 */

public final class Admin_AdminSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://ow2.petals.org/Admin/", "Admin");

    private Admin_AdminSOAP_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Admin_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Admin_Service ss = new Admin_Service(wsdlURL, SERVICE_NAME);
        Admin port = ss.getAdminSOAP();  
        
        {
        System.out.println("Invoking createProvider...");
        javax.xml.namespace.QName _createProvider_componentName = new javax.xml.namespace.QName("", "");
        javax.xml.namespace.QName _createProvider_providerName = new javax.xml.namespace.QName("", "");
        java.lang.String _createProvider_fractalProviderItfName = "";
        java.lang.String _createProvider_classProviderName = "";
        java.lang.String _createProvider__return = port.createProvider(_createProvider_componentName, _createProvider_providerName, _createProvider_fractalProviderItfName, _createProvider_classProviderName);
        System.out.println("createProvider.result=" + _createProvider__return);


        }
        {
        System.out.println("Invoking createClient...");
        javax.xml.namespace.QName _createClient_componentName = new javax.xml.namespace.QName("", "");
        javax.xml.namespace.QName _createClient_clientName = new javax.xml.namespace.QName("", "");
        java.lang.String _createClient_fractalClientItfName = "";
        java.lang.String _createClient_classClientName = "";
        java.lang.String _createClient__return = port.createClient(_createClient_componentName, _createClient_clientName, _createClient_fractalClientItfName, _createClient_classClientName);
        System.out.println("createClient.result=" + _createClient__return);


        }
        {
        System.out.println("Invoking createServiceEndpointOnSoapClient...");
        javax.xml.namespace.QName _createServiceEndpointOnSoapClient_providerName = new javax.xml.namespace.QName("", "");
        javax.xml.namespace.QName _createServiceEndpointOnSoapClient_serviceName = new javax.xml.namespace.QName("", "");
        java.lang.String _createServiceEndpointOnSoapClient_fractalServiceItfName = "";
        java.lang.String _createServiceEndpointOnSoapClient_classServiceName = "";
        java.lang.String _createServiceEndpointOnSoapClient_providerEndpointName = "";
        java.lang.String _createServiceEndpointOnSoapClient_fractalProviderEndpointItfName = "";
        java.lang.String _createServiceEndpointOnSoapClient_classProviderEndpointName = "";
        java.lang.String _createServiceEndpointOnSoapClient_classProviderEndpointBehaviourName = "";
        java.lang.String _createServiceEndpointOnSoapClient_wsdl = "";
        javax.xml.namespace.QName _createServiceEndpointOnSoapClient_clientName = new javax.xml.namespace.QName("", "");
        java.lang.String _createServiceEndpointOnSoapClient__return = port.createServiceEndpointOnSoapClient(_createServiceEndpointOnSoapClient_providerName, _createServiceEndpointOnSoapClient_serviceName, _createServiceEndpointOnSoapClient_fractalServiceItfName, _createServiceEndpointOnSoapClient_classServiceName, _createServiceEndpointOnSoapClient_providerEndpointName, _createServiceEndpointOnSoapClient_fractalProviderEndpointItfName, _createServiceEndpointOnSoapClient_classProviderEndpointName, _createServiceEndpointOnSoapClient_classProviderEndpointBehaviourName, _createServiceEndpointOnSoapClient_wsdl, _createServiceEndpointOnSoapClient_clientName);
        System.out.println("createServiceEndpointOnSoapClient.result=" + _createServiceEndpointOnSoapClient__return);


        }
        {
        System.out.println("Invoking createClientAndProvider...");
        javax.xml.namespace.QName _createClientAndProvider_componentName = new javax.xml.namespace.QName("", "");
        javax.xml.namespace.QName _createClientAndProvider_clientAndProviderName = new javax.xml.namespace.QName("", "");
        java.lang.String _createClientAndProvider_fractalClientAndProviderInterfaceName = "";
        java.lang.String _createClientAndProvider_classClientAndProviderName = "";
        java.lang.String _createClientAndProvider_fractalClientItfName = "";
        java.lang.String _createClientAndProvider_classClientName = "";
        java.lang.String _createClientAndProvider_fractalProviderItfName = "";
        java.lang.String _createClientAndProvider_classProviderName = "";
        java.lang.String _createClientAndProvider__return = port.createClientAndProvider(_createClientAndProvider_componentName, _createClientAndProvider_clientAndProviderName, _createClientAndProvider_fractalClientAndProviderInterfaceName, _createClientAndProvider_classClientAndProviderName, _createClientAndProvider_fractalClientItfName, _createClientAndProvider_classClientName, _createClientAndProvider_fractalProviderItfName, _createClientAndProvider_classProviderName);
        System.out.println("createClientAndProvider.result=" + _createClientAndProvider__return);


        }
        {
        System.out.println("Invoking createClientEndpoint...");
        javax.xml.namespace.QName _createClientEndpoint_clientName = new javax.xml.namespace.QName("", "");
        javax.xml.namespace.QName _createClientEndpoint_clientEndpointName = new javax.xml.namespace.QName("", "");
        java.lang.String _createClientEndpoint_fractalClientEndpointItfName = "";
        java.lang.String _createClientEndpoint_classClientEndpointName = "";
        java.lang.String _createClientEndpoint_classClientEndpointBehaviourName = "";
        java.lang.String _createClientEndpoint__return = port.createClientEndpoint(_createClientEndpoint_clientName, _createClientEndpoint_clientEndpointName, _createClientEndpoint_fractalClientEndpointItfName, _createClientEndpoint_classClientEndpointName, _createClientEndpoint_classClientEndpointBehaviourName);
        System.out.println("createClientEndpoint.result=" + _createClientEndpoint__return);


        }
        {
        System.out.println("Invoking importSoapEndpoint...");
        javax.xml.namespace.QName _importSoapEndpoint_providerName = new javax.xml.namespace.QName("", "");
        java.lang.String _importSoapEndpoint_soapAddress = "";
        java.lang.String _importSoapEndpoint_wsdl = "";
        java.lang.String _importSoapEndpoint__return = port.importSoapEndpoint(_importSoapEndpoint_providerName, _importSoapEndpoint_soapAddress, _importSoapEndpoint_wsdl);
        System.out.println("importSoapEndpoint.result=" + _importSoapEndpoint__return);


        }
        {
        System.out.println("Invoking createComponent...");
        javax.xml.namespace.QName _createComponent_componentName = new javax.xml.namespace.QName("", "");
        java.lang.String _createComponent_fractalItfName = "";
        java.lang.String _createComponent_classComponentName = "";
        java.lang.String _createComponent__return = port.createComponent(_createComponent_componentName, _createComponent_fractalItfName, _createComponent_classComponentName);
        System.out.println("createComponent.result=" + _createComponent__return);


        }
        {
        System.out.println("Invoking createMonitoringEndpoint...");
        javax.xml.namespace.QName _createMonitoringEndpoint_wsdmServiceName = new javax.xml.namespace.QName("", "");
        java.lang.String _createMonitoringEndpoint_wsdmProviderEndpointName = "";
        boolean _createMonitoringEndpoint_exposeInSoap = false;
        java.lang.String _createMonitoringEndpoint__return = port.createMonitoringEndpoint(_createMonitoringEndpoint_wsdmServiceName, _createMonitoringEndpoint_wsdmProviderEndpointName, _createMonitoringEndpoint_exposeInSoap);
        System.out.println("createMonitoringEndpoint.result=" + _createMonitoringEndpoint__return);


        }
        {
        System.out.println("Invoking createProviderEndpoint...");
        javax.xml.namespace.QName _createProviderEndpoint_serviceName = new javax.xml.namespace.QName("", "");
        java.lang.String _createProviderEndpoint_providerEndpointName = "";
        java.lang.String _createProviderEndpoint_fractalProviderEndpointItfName = "";
        java.lang.String _createProviderEndpoint_classProviderEndpointName = "";
        java.lang.String _createProviderEndpoint_classProviderEndpointBehaviourName = "";
        java.lang.String _createProviderEndpoint_wsdl = "";
        java.lang.String _createProviderEndpoint__return = port.createProviderEndpoint(_createProviderEndpoint_serviceName, _createProviderEndpoint_providerEndpointName, _createProviderEndpoint_fractalProviderEndpointItfName, _createProviderEndpoint_classProviderEndpointName, _createProviderEndpoint_classProviderEndpointBehaviourName, _createProviderEndpoint_wsdl);
        System.out.println("createProviderEndpoint.result=" + _createProviderEndpoint__return);


        }
        {
        System.out.println("Invoking wrapSoapEndpoint...");
        javax.xml.namespace.QName _wrapSoapEndpoint_providerName = new javax.xml.namespace.QName("", "");
        java.lang.String _wrapSoapEndpoint_soapAddress = "";
        java.lang.String _wrapSoapEndpoint_wsdl = "";
        java.util.List<java.lang.String> _wrapSoapEndpoint_interceptorClassName = null;
        javax.xml.namespace.QName _wrapSoapEndpoint_clientName = new javax.xml.namespace.QName("", "");
        java.lang.String _wrapSoapEndpoint__return = port.wrapSoapEndpoint(_wrapSoapEndpoint_providerName, _wrapSoapEndpoint_soapAddress, _wrapSoapEndpoint_wsdl, _wrapSoapEndpoint_interceptorClassName, _wrapSoapEndpoint_clientName);
        System.out.println("wrapSoapEndpoint.result=" + _wrapSoapEndpoint__return);


        }
        {
        System.out.println("Invoking createService...");
        javax.xml.namespace.QName _createService_providerName = new javax.xml.namespace.QName("", "");
        javax.xml.namespace.QName _createService_serviceName = new javax.xml.namespace.QName("", "");
        java.lang.String _createService_fractalServiceItfName = "";
        java.lang.String _createService_classServiceName = "";
        java.lang.String _createService__return = port.createService(_createService_providerName, _createService_serviceName, _createService_fractalServiceItfName, _createService_classServiceName);
        System.out.println("createService.result=" + _createService__return);


        }
        {
        System.out.println("Invoking createServiceEndpoint...");
        javax.xml.namespace.QName _createServiceEndpoint_providerName = new javax.xml.namespace.QName("", "");
        javax.xml.namespace.QName _createServiceEndpoint_serviceName = new javax.xml.namespace.QName("", "");
        java.lang.String _createServiceEndpoint_fractalServiceItfName = "";
        java.lang.String _createServiceEndpoint_classServiceName = "";
        java.lang.String _createServiceEndpoint_providerEndpointName = "";
        java.lang.String _createServiceEndpoint_fractalProviderEndpointItfName = "";
        java.lang.String _createServiceEndpoint_classProviderEndpointName = "";
        java.lang.String _createServiceEndpoint_classProviderEndpointBehaviourName = "";
        java.lang.String _createServiceEndpoint_wsdl = "";
        java.lang.String _createServiceEndpoint__return = port.createServiceEndpoint(_createServiceEndpoint_providerName, _createServiceEndpoint_serviceName, _createServiceEndpoint_fractalServiceItfName, _createServiceEndpoint_classServiceName, _createServiceEndpoint_providerEndpointName, _createServiceEndpoint_fractalProviderEndpointItfName, _createServiceEndpoint_classProviderEndpointName, _createServiceEndpoint_classProviderEndpointBehaviourName, _createServiceEndpoint_wsdl);
        System.out.println("createServiceEndpoint.result=" + _createServiceEndpoint__return);


        }
        {
        System.out.println("Invoking addSoapListener...");
        javax.xml.namespace.QName _addSoapListener_clientEndpointName = new javax.xml.namespace.QName("", "");
        java.lang.String _addSoapListener__return = port.addSoapListener(_addSoapListener_clientEndpointName);
        System.out.println("addSoapListener.result=" + _addSoapListener__return);


        }
        {
        System.out.println("Invoking exposeInSoapOnClient...");
        javax.xml.namespace.QName _exposeInSoapOnClient_serviceName = new javax.xml.namespace.QName("", "");
        java.lang.String _exposeInSoapOnClient_providerEndpointName = "";
        javax.xml.namespace.QName _exposeInSoapOnClient_clientName = new javax.xml.namespace.QName("", "");
        java.lang.String _exposeInSoapOnClient__return = port.exposeInSoapOnClient(_exposeInSoapOnClient_serviceName, _exposeInSoapOnClient_providerEndpointName, _exposeInSoapOnClient_clientName);
        System.out.println("exposeInSoapOnClient.result=" + _exposeInSoapOnClient__return);


        }

        System.exit(0);
    }

}
