
/*
 * 
 */

package org.petals.ow2.admin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.2
 * Fri Jan 14 11:43:20 CET 2011
 * Generated source version: 2.2.2
 * 
 */


@WebServiceClient(name = "Admin", 
                  wsdlLocation = "file:/Users/chamerling/Developpement/petalslink/trunk/research/commons/dsb/modules/dependencies-fork/wsdm-monitoring/esb-monitoring/base-monitoring-wsclient/src/main/resources/wsdl/WSDMMonitoringAdmin.wsdl",
                  targetNamespace = "http://ow2.petals.org/Admin/") 
public class Admin_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ow2.petals.org/Admin/", "Admin");
    public final static QName AdminSOAP = new QName("http://ow2.petals.org/Admin/", "AdminSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/chamerling/Developpement/petalslink/trunk/research/commons/dsb/modules/dependencies-fork/wsdm-monitoring/esb-monitoring/base-monitoring-wsclient/src/main/resources/wsdl/WSDMMonitoringAdmin.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/Users/chamerling/Developpement/petalslink/trunk/research/commons/dsb/modules/dependencies-fork/wsdm-monitoring/esb-monitoring/base-monitoring-wsclient/src/main/resources/wsdl/WSDMMonitoringAdmin.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Admin_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Admin_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Admin_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns Admin
     */
    @WebEndpoint(name = "AdminSOAP")
    public Admin getAdminSOAP() {
        return super.getPort(AdminSOAP, Admin.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Admin
     */
    @WebEndpoint(name = "AdminSOAP")
    public Admin getAdminSOAP(WebServiceFeature... features) {
        return super.getPort(AdminSOAP, Admin.class, features);
    }

}
