
package org.petals.ow2.echo;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.1.4
 * Wed Jul 29 10:41:28 CEST 2009
 * Generated source version: 2.1.4
 * 
 */
 
public class Echo_EchoSOAP_Server{

    public Echo_EchoSOAP_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new EchoImpl();
        String address = "http://localhost:9001/echo";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new Echo_EchoSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
