
/*
 * 
 */

package org.ow2.petals.notifier;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import org.oasis_open.docs.wsn.bw_2.NotificationConsumer;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Aug 10 07:04:16 CEST 2009
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "NotifierService", 
		wsdlLocation = "notifier.wsdl",
		targetNamespace = "http://petals.ow2.org/notifier") 
		public class NotifierService extends Service {

	public final static URL WSDL_LOCATION;
	public final static QName SERVICE = new QName("http://petals.ow2.org/notifier", "NotifierService");
	public final static QName NotifierEndpoint = new QName("http://petals.ow2.org/notifier", "NotifierEndpoint");
	static {
		URL url = null;

		url = NotifierService.class.getClassLoader().getResource("notifier.wsdl");

		WSDL_LOCATION = url;
	}

	public NotifierService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public NotifierService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public NotifierService() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return
	 *     returns NotificationConsumer
	 */
	@WebEndpoint(name = "NotifierEndpoint")
	public NotificationConsumer getNotifierEndpoint() {
		return super.getPort(NotifierEndpoint, NotificationConsumer.class);
	}

	/**
	 * 
	 * @param features
	 *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
	 * @return
	 *     returns NotificationConsumer
	 */
	@WebEndpoint(name = "NotifierEndpoint")
	public NotificationConsumer getNotifierEndpoint(WebServiceFeature... features) {
		return super.getPort(NotifierEndpoint, NotificationConsumer.class, features);
	}

}
