
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.oasis_open.docs.wsn.bw_2;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.ow2.petals.notifier.NotificationConsumerDecorator;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Aug 10 07:04:16 CEST 2009
 * Generated source version: 2.1.3
 * 
 */

@javax.jws.WebService(
		serviceName = "NotifierService",
		portName = "NotifierEndpoint",
		targetNamespace = "http://petals.ow2.org/notifier",
		wsdlLocation = "notifier.wsdl",
		endpointInterface = "org.oasis_open.docs.wsn.bw_2.NotificationConsumer")

		public class NotificationConsumerImpl implements NotificationConsumer {

	private static final Logger LOG = Logger.getLogger(NotificationConsumerImpl.class.getName());

	private NotificationConsumerDecorator decorator;


	public NotificationConsumerImpl(NotificationConsumerDecorator decorator) {
		this.decorator = decorator;
	}

	/* (non-Javadoc)
	 * @see org.oasis_open.docs.wsn.bw_2.NotificationConsumer#notify(org.oasis_open.docs.wsn.b_2.Notify  notify )*
	 */
	public void notify(org.oasis_open.docs.wsn.b_2.Notify notify) { 
		LOG.info("Executing operation notify");
		if(this.decorator != null) {
			this.decorator.notify(notify);
		} else {
			LOG.info("Decorator is null");
		}
	}

}
