
package org.oasis_open.docs.wsn.bw_2;

import javax.xml.ws.Endpoint;

import org.ow2.petals.notifier.NotificationConsumerDecorator;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Aug 10 07:04:16 CEST 2009
 * Generated source version: 2.1.3
 * 
 */
 
public class NotificationConsumer_NotifierEndpoint_Server{

	private Endpoint ep = null;
	
    public NotificationConsumer_NotifierEndpoint_Server(NotificationConsumerDecorator decorator) throws Exception {
        System.out.println("Starting Notifier Service");
        Object implementor = new NotificationConsumerImpl(decorator);
        String address = "http://localhost:9001/NotifierEndpoint";
        ep = Endpoint.publish(address, implementor);
        System.out.println("Notifier Service ready..."); 
    }
    
    public NotificationConsumer_NotifierEndpoint_Server(NotificationConsumerDecorator decorator, String address) throws Exception {
        System.out.println("Starting Notifier Service");
        Object implementor = new NotificationConsumerImpl(decorator);
        ep = Endpoint.publish(address, implementor);
        System.out.println("Notifier Service ready..."); 
    }
    
    public void shutdown() {
    	ep.stop();
    }
    
    public static void main(String args[]) throws Exception { 
        new NotificationConsumer_NotifierEndpoint_Server(null);
        
//        Thread.sleep(5 * 60 * 1000); 
//        System.out.println("Server exiting");
//        System.exit(0);
    }
}
