
package org.ow2.petals.kernel.ws.api;

import javax.xml.ws.Endpoint;

import org.ow2.petals.endpoint.service.EndpointServiceDecorator;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Sep 23 13:48:03 CEST 2009
 * Generated source version: 2.1.3
 * 
 */
 
public class EndpointService_EndpointServicePort_Server{

	private Endpoint ep = null;
	
    public EndpointService_EndpointServicePort_Server(EndpointServiceDecorator decorator) throws Exception {
        System.out.println("Starting Server");
        Object implementor = new EndpointServiceImpl(decorator);
        String address = "http://localhost:7600/petals/ws/EndpointService";
        ep = Endpoint.publish(address, implementor);
    }
    
    public EndpointService_EndpointServicePort_Server(EndpointServiceDecorator decorator, String address) throws Exception {
        System.out.println("Starting Server");
        Object implementor = new EndpointServiceImpl(decorator);
       
        ep = Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new EndpointService_EndpointServicePort_Server(null);
        System.out.println("Server ready..."); 
        
//        Thread.sleep(5 * 60 * 1000); 
//        System.out.println("Server exiting");
//        System.exit(0);
    }
    
    public void shutdown() {
    	ep.stop();
    }
}
