
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.ow2.petals.kernel.ws.api;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.ow2.petals.endpoint.service.EndpointServiceDecorator;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Sep 23 13:48:03 CEST 2009
 * Generated source version: 2.1.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "EndpointServiceService",
                      portName = "EndpointServicePort",
                      targetNamespace = "http://api.ws.kernel.petals.ow2.org/",
                      wsdlLocation = "PetalsEndpointService.wsdl",
                      endpointInterface = "org.ow2.petals.kernel.ws.api.EndpointService")
                      
public class EndpointServiceImpl implements EndpointService {

    private static final Logger LOG = Logger.getLogger(EndpointServiceImpl.class.getName());
    
    private EndpointServiceDecorator decorator;
    
    public EndpointServiceImpl(EndpointServiceDecorator decorator) {
    	this.decorator = decorator;
    }

    /* (non-Javadoc)
     * @see org.ow2.petals.kernel.ws.api.EndpointService#query(org.ow2.petals.ws._1.EndpointQuery  arg0 )*
     */
    public java.util.List<org.ow2.petals.ws._1.Endpoint> query(org.ow2.petals.ws._1.EndpointQuery arg0) throws PEtALSWebServiceException_Exception    { 
        LOG.info("Executing operation query");
        System.out.println(arg0);
        java.util.List<org.ow2.petals.ws._1.Endpoint> query = null;
        if(this.decorator != null) {
        	query = this.decorator.query(arg0);
        }
        return query;
        //throw new PEtALSWebServiceException_Exception("PEtALSWebServiceException...");
    }

    /* (non-Javadoc)
     * @see org.ow2.petals.kernel.ws.api.EndpointService#getEndpoints(*
     */
    public java.util.List<org.ow2.petals.ws._1.Endpoint> getEndpoints() throws PEtALSWebServiceException_Exception    { 
        LOG.info("Executing operation getEndpoints");
        java.util.List<org.ow2.petals.ws._1.Endpoint> endpoints = null;
        if(this.decorator != null) {
        	endpoints = this.decorator.getEndpoints();
        }
        return endpoints;
        //throw new PEtALSWebServiceException_Exception("PEtALSWebServiceException...");
    }

}
