package org.ow2.petals.kernel.ws.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Sep 23 13:48:03 CEST 2009
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://api.ws.kernel.petals.ow2.org/", name = "EndpointService")
@XmlSeeAlso({org.ow2.petals.ws._1.ObjectFactory.class,ObjectFactory.class})
public interface EndpointService {

    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://api.ws.kernel.petals.ow2.org/", className = "org.ow2.petals.kernel.ws.api.QueryResponse")
    @RequestWrapper(localName = "query", targetNamespace = "http://api.ws.kernel.petals.ow2.org/", className = "org.ow2.petals.kernel.ws.api.Query")
    @WebResult(name = "endpoints", targetNamespace = "")
    @WebMethod
    public java.util.List<org.ow2.petals.ws._1.Endpoint> query(
        @WebParam(name = "arg0", targetNamespace = "")
        org.ow2.petals.ws._1.EndpointQuery arg0
    ) throws PEtALSWebServiceException_Exception;

    @ResponseWrapper(localName = "getEndpointsResponse", targetNamespace = "http://api.ws.kernel.petals.ow2.org/", className = "org.ow2.petals.kernel.ws.api.GetEndpointsResponse")
    @RequestWrapper(localName = "getEndpoints", targetNamespace = "http://api.ws.kernel.petals.ow2.org/", className = "org.ow2.petals.kernel.ws.api.GetEndpoints")
    @WebResult(name = "endpoints", targetNamespace = "")
    @WebMethod
    public java.util.List<org.ow2.petals.ws._1.Endpoint> getEndpoints() throws PEtALSWebServiceException_Exception;
}
