
/*
 * 
 */

package org.ow2.petals.kernel.ws.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Sep 23 13:48:03 CEST 2009
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "EndpointServiceService", 
		wsdlLocation = "PetalsEndpointService.wsdl",
		targetNamespace = "http://api.ws.kernel.petals.ow2.org/") 
		public class EndpointServiceService extends Service {

	public final static URL WSDL_LOCATION;
	public final static QName SERVICE = new QName("http://api.ws.kernel.petals.ow2.org/", "EndpointServiceService");
	public final static QName EndpointServicePort = new QName("http://api.ws.kernel.petals.ow2.org/", "EndpointServicePort");
	static {
		URL url = null;
		url = EndpointServiceService.class.getClassLoader().getResource("PetalsEndpointService.wsdl");

		WSDL_LOCATION = url;
	}

	public EndpointServiceService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public EndpointServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public EndpointServiceService() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return
	 *     returns EndpointService
	 */
	@WebEndpoint(name = "EndpointServicePort")
	public EndpointService getEndpointServicePort() {
		return super.getPort(EndpointServicePort, EndpointService.class);
	}

	/**
	 * 
	 * @param features
	 *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
	 * @return
	 *     returns EndpointService
	 */
	@WebEndpoint(name = "EndpointServicePort")
	public EndpointService getEndpointServicePort(WebServiceFeature... features) {
		return super.getPort(EndpointServicePort, EndpointService.class, features);
	}

}
