
package org.ow2.petals.kernel.ws.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Sep 23 13:48:03 CEST 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "PEtALSWebServiceException", targetNamespace = "http://api.ws.kernel.petals.ow2.org/")
public class PEtALSWebServiceException_Exception extends Exception {
    public static final long serialVersionUID = 20090923134803L;
    
    private org.ow2.petals.kernel.ws.api.PEtALSWebServiceException pEtALSWebServiceException;

    public PEtALSWebServiceException_Exception() {
        super();
    }
    
    public PEtALSWebServiceException_Exception(String message) {
        super(message);
    }
    
    public PEtALSWebServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PEtALSWebServiceException_Exception(String message, org.ow2.petals.kernel.ws.api.PEtALSWebServiceException pEtALSWebServiceException) {
        super(message);
        this.pEtALSWebServiceException = pEtALSWebServiceException;
    }

    public PEtALSWebServiceException_Exception(String message, org.ow2.petals.kernel.ws.api.PEtALSWebServiceException pEtALSWebServiceException, Throwable cause) {
        super(message, cause);
        this.pEtALSWebServiceException = pEtALSWebServiceException;
    }

    public org.ow2.petals.kernel.ws.api.PEtALSWebServiceException getFaultInfo() {
        return this.pEtALSWebServiceException;
    }
}
